name: Build and deploy

on:
  push:
    # branches: [ beat-dispatch ]
    # tags:
    #  - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Node dependencies
      run: yarn install --frozen-lockfile

    - name: Write version from REF to file
      working-directory: ./src
      run: 'echo "${{github.ref_name}}" >version.txt'

    - name: Build web app
      run: node build.js

    - name: Build Docker image
      run: docker build --platform=linux/amd64 -t csound-live .

    - name: Push Docker image to Amazon ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-central-1
        local-image: csound-live
        image: csound-live

    # - name: Invoke deployment hook
    #   uses: distributhor/workflow-webhook@v1
    #   env:
    #     webhook_url: ${{ secrets.WEBHOOK_URL }}
    #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
    #     data: '{ "secret": "${{ secrets.WEBHOOK_SECRET }}"  }'
       
